<Project Sdk="Microsoft.NET.Sdk.Razor">
  <!--<Project Sdk="Microsoft.NET.Sdk.Razor" InitialTargets="BridgeTooFarReferencePathConfigCheck">-->

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <!--<EnableDefaultContentItems>False</EnableDefaultContentItems>-->
    <Description>The JSopX™ Open ProjectX Bridge Too Far Solution, is evolving into a centralized hub for managing and sharing ALL assets and documentation, across all other JSopX™ Open Project EXperience Projects, including all Class Libraries, RCLs, server-side and client-side projects. </Description>
    <PackageReleaseNotes>MVP v 1.0 release for the JSopX™ Open ProjectX Bridge Too Far Solution.

The JSopX™ Open ProjectX Bridge Too Far Solution, is evolving into a centralized hub for managing and sharing ALL assets and documentation, across all other JSopX™ Open Project EXperience Projects, including all Class Libraries, RCLs, server-side and client-side projects. </PackageReleaseNotes>
    <Copyright>© 2024 JSopX™ by Jason Silvestri</Copyright>
    <PackageProjectUrl>https://github.com/JasonSilvestri/JSopX.BridgeTooFar</PackageProjectUrl>
    <RepositoryUrl>https://github.com/JasonSilvestri/JSopX.BridgeTooFar.git</RepositoryUrl>
    <Product>JSopX™ Bridge Too Far Open Project EXperience</Product>
    <Company>jSilvestri.com</Company>
    <Authors>Jason Silvestri</Authors>
    <Title>JSopX™ Bridge Too Far Open Project EXperience</Title>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.8" />
  </ItemGroup>

  <!--<ItemGroup>
    <Content Include="wwwroot\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>-->

  <ItemGroup>
    <Folder Include="DocsX\jsopx.WebAPI\Master\p1\v1\Includes\Content\Template\SubTemplate\" />
    <Folder Include="DocsX\jsopx.WebAPI\Master\p1\v1\Includes\Templates\SubTemplates\" />
    <Folder Include="DocsX\jsopx.ClassLibrary\Master\p1\v1\Includes\Content\Template\SubTemplate\" />
    <Folder Include="DocsX\jsopx.ClassLibrary\Master\p1\v1\Includes\Templates\SubTemplates\" />
    <Folder Include="DocsX\jsopx.BridgeTooFar\Master\p1\v1\Includes\Content\Template\SubTemplate\" />
    <Folder Include="DocsX\jsopx.BridgeTooFar\Master\p1\v1\Includes\Templates\SubTemplates\" />
    <Folder Include="Docs\jsopx.BridgeTooFar\Master\p1\v1\" />
    <Folder Include="Docs\JSopX\Master\Phases\" />
  </ItemGroup>


  <!--Option 1: Original--><!--

  --><!-- Import if the file exists --><!--
  <Import Project="..\PathConfig.targets" Condition="Exists('..\PathConfig.targets')" />

  --><!-- Default static project references if the file does not exist --><!--
  <ItemGroup Condition="Exists('..\PathConfig.targets')">
    <ProjectReference Include="$(BridgeTooFarClassLibraryPath)\JSopX.ClassLibrary.csproj" />
  </ItemGroup>


  --><!-- Default static project references if the file does not exist --><!--
  <ItemGroup Condition="!Exists('..\PathConfig.targets')">
    <ProjectReference Include="..\JSopX.ClassLibrary\JSopX.ClassLibrary\JSopX.ClassLibrary.csproj" />
  </ItemGroup>-->

</Project>
